# Change these first
owner: Shapiro-Negotiations-Institute
repo: upptime # The name of this repository

sites:
  - name: Shapiro Negotiations Institute
    url: https://www.shapironegotiations.com/

  - name: Shapiro Negotiations Institute | Stage
    url: https://stage.shapironegotiations.com/

  - name: Shapiro Negotiations Institute - Programs
    url: http://programs.shapironegotiations.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.shapironegotiations.com
  # baseUrl: /your-repo-name
  logoUrl: https://www.shapironegotiations.com/wp-content/uploads/2025/10/SNI-branding_2024_SNI-Standard-Logo-no-wordsx.png
  name: Shapiro Negotiations Institute Status
  introTitle: "**SNI** Shapiro Negotiations Institute Status Page"
  introMessage: Shapiro Negotiations Institute (SNI) is the premier global provider of sales, influence, and negotiation training and consulting. Founded in 1995, and having trained over 250,000 professionals, we are the leader in training, consulting and keynotes in these three content areas. We focus on the bottom line, the people, and the tools that drive success for the world’s leading organizations.
  navbar:
    - title: Status
      href: /


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
